import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, hero, overview, products }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        {hero}
        {overview}
        {products}
      </body>
    </html>
  );
}
